### ISSUE TITLE
cannot cast default spinner to customspinner

### ISSUE THREAD

**Issue by navotera** [piotrek1543/CustomSpinner#4]
![image](https://cloud.githubusercontent.com/assets/1424851/24484476/ff14e028-1530-11e7-8577-90f4295f3d4f.png)

**Comment by piotrek1543** [comment]
@navotera it see that in your layout you're using `android.view.Spinner` instead of `CustomSpinner`. 
Go to your `xml` file and change type of view. The problem would be than solved.

Why casting is wrong? Default Spinner has no features that `CustomSpinner` has like method `initialize` so Android would not recognize every attribute or method which is not included in default `Spinner` class. 

Cheers!

**Comment by navotera** [comment]
**here my view :** 
```
  <CustomSpinner
        android:id="@+id/semester_spinner"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="16dp"
        app:layout_constraintTop_toTopOf="parent"
        android:layout_marginRight="16dp"
        app:layout_constraintRight_toRightOf="parent" />
```


**my code on class :** 
```
     CustomSpinner spinner = (CustomSpinner) rootView.findViewById(R.id.semester_spinner);
        String[] types = new String[]{"1","2","3"};
        spinner.initializeStringValues(types);
```


**error i got :** 
```
03-30 06:49:49.583 16707-16707/navotera.syasep E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: navotera.syasep, PID: 16707
                                                                 android.view.InflateException: Binary XML file line #25: Error inflating class CustomSpinner
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
```

**Comment by piotrek1543** [comment]
@navotera well, error you got is not related to casting.

**First attempt**
Change `android:layout_width="0dp"` with `android:layout_width="wrap_content"` or `match_parent` attr.

**Second attempt**
Change `ConstraintLayout` to `LinearLayout`, then to `RelativeLayout`.  I haven't tested my library with `ConstraintLayout`, but I think that error may be related with inflating in this kind of `ViewGroup`.

**Comment by navotera** [comment]
yes it works i change it to relativeLayout, but the spinner is not very responsive on the android monitor with logcat option picked "No Filter" it show this error : 
```

03-30 07:55:30.960 4238-4238/navotera.syasep W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
03-30 07:55:30.961 4238-4238/navotera.syasep I/Choreographer: Skipped 516 frames!  The application may be doing too much work on its main thread.
03-30 07:55:30.966 4238-4238/navotera.syasep D/CustomSpinner: onWindowFocusChanged
03-30 07:55:30.966 4238-4238/navotera.syasep I/CustomSpinner: closing popup
03-30 07:55:30.968 1580-3334/system_process W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@2bf71b6b attribute=null, token = android.os.BinderProxy@1fa3fa5f

```

**Comment by navotera** [comment]
here is my layout : 
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent" android:layout_height="match_parent">

    <com.piotrek.customspinner.CustomSpinner
        android:id="@+id/semester_spinner"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
</RelativeLayout>
```
my java class fragment code : 
```

 @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {


        rootView = inflater.inflate(R.layout.d, container, false);
        this.container = container;

        // Spinner element
        final CustomSpinner spinner = (CustomSpinner) rootView.findViewById(R.id.semester_spinner);

        String[] types = new String[]{"1","2","3"};
        spinner.initializeStringValues(types);

        return rootView;
    }
```

**Comment by navotera** [comment]
i think this error message need attention : 
`03-30 07:55:30.960 4238-4238/navotera.syasep W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.`
and this : 
`03-30 07:55:30.968 1580-3334/system_process W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@2bf71b6b attribute=null, token = android.os.BinderProxy@1fa3fa5f`

**Comment by piotrek1543** [comment]
@navotera glad to hear it's working now. I will check these logs. Thanks
